### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by BastiJoe** [UdK-VPT/BIM2Modelica#6]
Hi guys,
i am trying to get the toolchain running.

When trying to run CoTeTo with one of the UniTest Cases i get the following error:

INFO: Starting CoTeTo.Controller from file C:\Users\A200209509\Downloads\CoTeTo-master\CoTeTo-master\CoTeTo\Controller.py, version 1.0
INFO: IFCFile - loading C:/Users/user/Downloads/BIM2Modelica-master/BIM2Modelica-master/IFC/IFC2X3/UdKB_Unit_Test_Cases/MultiZoneBuilding.ifc
INFO: determine building model information for file: C:/Users/user/Downloads/BIM2Modelica-master/BIM2Modelica-master/IFC/IFC2X3/UdKB_Unit_Test_Cases/MultiZoneBuilding.ifc
CRITICAL: An unhandled exception occured
****************************************
Traceback (most recent call last):
  File "C:\Users\user\Downloads\CoTeTo-master\CoTeTo-master\CoTeTo\GUI.py", line 269, in executeGenerator
    x = self.activeGenerator.execute(uriList, outputBase)
  File "C:\Users\user\Downloads\CoTeTo-master\CoTeTo-master\CoTeTo\Generator.py", line 262, in execute
    self.executeFilter()
  File "C:\Users\user\Downloads\CoTeTo-master\CoTeTo-master\CoTeTo\Generator.py", line 187, in executeFilter
    function(self.data, self.controller.systemCfg, self.cfg, self.logger)
  File "C:\Users\user\Downloads\CoTeTo-master\CoTeTo-master\Generators\IFC_MultiZoneBuildings_Modelica\Filters\Filter01.py", line 497, in filter01
    dataModel = mapIFCtoBuildingDataModel(fileData['IfcData'], fileName)
  File "C:\Users\user\Downloads\CoTeTo-master\CoTeTo-master\Generators\IFC_MultiZoneBuildings_Modelica\Filters\Filter01.py", line 61, in mapIFCtoBuildingDataModel
    mesh = DataClasses.Mesh(toposhape)
  File "C:\Users\user\Downloads\CoTeTo-master\CoTeTo-master\Generators\IFC_MultiZoneBuildings_Modelica\Filters\IfcLib\DataClasses.py", line 120, in __init__
    for i in range(1, nTri + 1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
****************************************

Do you have any idea?
Thank you very much.

Best regards

**Comment by BastiJoe** [comment]
I added an if clause in Dataclasses.py
it is working now

            if nTri is not None:
                for i in range(1, nTri + 1):
